-- 코드를 입력하세요
SELECT DISTINCT O1.USER_ID AS USER_ID, O1.PRODUCT_ID AS PRODUCT_ID
FROM ONLINE_SALE O1
WHERE
    (
        SELECT COUNT(*)
        FROM ONLINE_SALE O2
        WHERE O1.USER_ID = O2.USER_ID AND O1.PRODUCT_ID = O2.PRODUCT_ID
    ) > 1 -- USER_ID와 PRODUCT_ID가 동일한 것이 2개 이상 있는 것을 찾아냄
ORDER BY USER_ID, PRODUCT_ID DESC;