-- 코드를 작성해주세요
SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, ABS(A.SIZE_OF_COLONY - B.MAX_SIZE) AS YEAR_DEV, A.ID
FROM ECOLI_DATA A
    LEFT JOIN
    (
        SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, MAX(A.SIZE_OF_COLONY) AS MAX_SIZE
        FROM ECOLI_DATA A
        GROUP BY YEAR(A.DIFFERENTIATION_DATE)
    ) B -- 연도별로 가장 큰 대장균의 크기 구하기
    ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR -- 연도가 동일한 A에 B.MAX_SIZE를 합침
ORDER BY YEAR, YEAR_DEV
